import type { MetadataRoute } from 'next';

import { contentType, generateImageMetadata } from '@/app/icon';
import { SITE_DESCRIPTION, SITE_TITLE } from '@/lib/site';

/*
 * `/manifest.webmanifest` — emitted by Next from this file at build time.
 *
 * The App Router `manifest` file convention auto-injects
 * `<link rel="manifest" href="/manifest.webmanifest">` into every route's
 * <head>, which is what makes the site installable as a PWA (add-to-home-
 * screen on Android, web-app-install banners). No static asset in `public/`
 * — the manifest is generated, same pattern as `robots.ts` / `sitemap.ts`.
 *
 * Colors come from the design tokens in `app/globals.css`:
 *   - background_color `#0a0a0a` = `--color-bg` (dark, the SSR default theme)
 *   - theme_color      `#f97316` = the orange brand accent (matches the
 *     accent period in `app/apple-icon.tsx` / `app/opengraph-image.tsx`)
 *
 * Icons are generated by `app/icon.tsx` (`next/og` + `generateImageMetadata`),
 * which serves each size at the `/icon/<id>` route convention — NOT static
 * `public/icon-*.png` assets (none exist). We derive the manifest's `icons`
 * entries from that same `generateImageMetadata` so the `src` paths can never
 * drift from the routes Next actually serves (the original static-path
 * references 404'd — see #195). OG/Twitter image references here are owned
 * by #142.
 */
export const dynamic = 'force-static';

export default function manifest(): MetadataRoute.Manifest {
  return {
    name: SITE_TITLE,
    short_name: SITE_TITLE,
    description: SITE_DESCRIPTION,
    start_url: '/',
    display: 'standalone',
    background_color: '#0a0a0a',
    theme_color: '#f97316',
    icons: generateImageMetadata().map(({ id, size }) => ({
      src: `/icon/${id}`,
      sizes: `${size.width}x${size.height}`,
      type: contentType,
    })),
  };
}
