import type { MetadataRoute } from 'next';

import { contentType, generateImageMetadata } from '@/app/icon';
import { contentType as ogContentType, size as ogSize } from '@/app/opengraph-image';
import { SITE_DESCRIPTION, SITE_TITLE } from '@/lib/site';

/*
 * `/manifest.webmanifest` — emitted by Next from this file at build time.
 *
 * The App Router `manifest` file convention auto-injects
 * `<link rel="manifest" href="/manifest.webmanifest">` into every route's
 * <head>, which is what makes the site installable as a PWA (add-to-home-
 * screen on Android, web-app-install banners). No static asset in `public/`
 * — the manifest is generated, same pattern as `robots.ts` / `sitemap.ts`.
 *
 * Colors come from the design tokens in `app/globals.css`:
 *   - background_color `#0a0a0a` = `--color-bg` (dark, the SSR default theme)
 *   - theme_color      `#f97316` = the orange brand accent (matches the
 *     accent period in `app/apple-icon.tsx` / `app/opengraph-image.tsx`)
 *
 * Icons are generated by `app/icon.tsx` (`next/og` + `generateImageMetadata`),
 * which serves each size at the `/icon/<id>` route convention — NOT static
 * `public/icon-*.png` assets (none exist). We derive the manifest's `icons`
 * entries from that same `generateImageMetadata` so the `src` paths can never
 * drift from the routes Next actually serves (the original static-path
 * references 404'd — see #195).
 *
 * `screenshots` reference the site-wide Open Graph image (`app/opengraph-image
 * .tsx`, served at `/opengraph-image`) so the PWA install prompt on Android
 * matches the 1200×630 social-sharing preview, keeping brand consistency
 * across app drawers and social feeds (see #142). Both `wide` and `narrow`
 * form factors point at the same image. `sizes` / `type` are pulled from the
 * OG route's own `size` / `contentType` exports so they can't drift from what
 * Next actually serves — same import-driven discipline as the `icons` block.
 */
export const dynamic = 'force-static';

export default function manifest(): MetadataRoute.Manifest {
  return {
    name: SITE_TITLE,
    short_name: SITE_TITLE,
    description: SITE_DESCRIPTION,
    start_url: '/',
    display: 'standalone',
    background_color: '#0a0a0a',
    theme_color: '#f97316',
    icons: generateImageMetadata().map(({ id, size }) => ({
      src: `/icon/${id}`,
      sizes: `${size.width}x${size.height}`,
      type: contentType,
    })),
    screenshots: [
      {
        src: '/opengraph-image',
        sizes: `${ogSize.width}x${ogSize.height}`,
        type: ogContentType,
        form_factor: 'wide',
      },
      {
        src: '/opengraph-image',
        sizes: `${ogSize.width}x${ogSize.height}`,
        type: ogContentType,
        form_factor: 'narrow',
      },
    ],
  };
}
